services:
  db:
    image: mysql:8.0
    container_name: mudi_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mudi
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345678
    volumes:
      - ${PWD}/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend